name: Cyberexblack
favicon: null
layout_spectrum: 0.16700681415386498
typography_spectrum: 0.6703175948932767
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e9e9cb'
    - '#8d8e81'
    - '#462521'
    - '#a6574d'
  brandStrength: 0.125
  lightness: 0.879827135708183
  saturation: 0.6875
  rhythmicContrast: 0.8737969025969505
purpose: []
